// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v3.21.12
// source: server/pkg/protobuf/preview_proxy.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	PreviewProxy_DownloadThumbnails_FullMethodName = "/PreviewProxy/DownloadThumbnails"
)

// PreviewProxyClient is the client API for PreviewProxy service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type PreviewProxyClient interface {
	DownloadThumbnails(ctx context.Context, in *DownloadThumbnailReq, opts ...grpc.CallOption) (*DownloadThumbnailRes, error)
}

type previewProxyClient struct {
	cc grpc.ClientConnInterface
}

func NewPreviewProxyClient(cc grpc.ClientConnInterface) PreviewProxyClient {
	return &previewProxyClient{cc}
}

func (c *previewProxyClient) DownloadThumbnails(ctx context.Context, in *DownloadThumbnailReq, opts ...grpc.CallOption) (*DownloadThumbnailRes, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DownloadThumbnailRes)
	err := c.cc.Invoke(ctx, PreviewProxy_DownloadThumbnails_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// PreviewProxyServer is the server API for PreviewProxy service.
// All implementations must embed UnimplementedPreviewProxyServer
// for forward compatibility.
type PreviewProxyServer interface {
	DownloadThumbnails(context.Context, *DownloadThumbnailReq) (*DownloadThumbnailRes, error)
	mustEmbedUnimplementedPreviewProxyServer()
}

// UnimplementedPreviewProxyServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedPreviewProxyServer struct{}

func (UnimplementedPreviewProxyServer) DownloadThumbnails(context.Context, *DownloadThumbnailReq) (*DownloadThumbnailRes, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DownloadThumbnails not implemented")
}
func (UnimplementedPreviewProxyServer) mustEmbedUnimplementedPreviewProxyServer() {}
func (UnimplementedPreviewProxyServer) testEmbeddedByValue()                      {}

// UnsafePreviewProxyServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to PreviewProxyServer will
// result in compilation errors.
type UnsafePreviewProxyServer interface {
	mustEmbedUnimplementedPreviewProxyServer()
}

func RegisterPreviewProxyServer(s grpc.ServiceRegistrar, srv PreviewProxyServer) {
	// If the following call pancis, it indicates UnimplementedPreviewProxyServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&PreviewProxy_ServiceDesc, srv)
}

func _PreviewProxy_DownloadThumbnails_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DownloadThumbnailReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PreviewProxyServer).DownloadThumbnails(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PreviewProxy_DownloadThumbnails_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PreviewProxyServer).DownloadThumbnails(ctx, req.(*DownloadThumbnailReq))
	}
	return interceptor(ctx, in, info, handler)
}

// PreviewProxy_ServiceDesc is the grpc.ServiceDesc for PreviewProxy service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var PreviewProxy_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "PreviewProxy",
	HandlerType: (*PreviewProxyServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "DownloadThumbnails",
			Handler:    _PreviewProxy_DownloadThumbnails_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "server/pkg/protobuf/preview_proxy.proto",
}
