// Code generated by MockGen. DO NOT EDIT.
// Source: internal/api/youtube_api.go

// Package api is a generated GoMock package.
package api

import (
	context "context"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
)

// MockYoutubeAPI is a mock of YoutubeAPI interface.
type MockYoutubeAPI struct {
	ctrl     *gomock.Controller
	recorder *MockYoutubeAPIMockRecorder
}

// MockYoutubeAPIMockRecorder is the mock recorder for MockYoutubeAPI.
type MockYoutubeAPIMockRecorder struct {
	mock *MockYoutubeAPI
}

// NewMockYoutubeAPI creates a new mock instance.
func NewMockYoutubeAPI(ctrl *gomock.Controller) *MockYoutubeAPI {
	mock := &MockYoutubeAPI{ctrl: ctrl}
	mock.recorder = &MockYoutubeAPIMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockYoutubeAPI) EXPECT() *MockYoutubeAPIMockRecorder {
	return m.recorder
}

// GetThumbnail mocks base method.
func (m *MockYoutubeAPI) GetThumbnail(ctx context.Context, videoURL string) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetThumbnail", ctx, videoURL)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetThumbnail indicates an expected call of GetThumbnail.
func (mr *MockYoutubeAPIMockRecorder) GetThumbnail(ctx, videoURL interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetThumbnail", reflect.TypeOf((*MockYoutubeAPI)(nil).GetThumbnail), ctx, videoURL)
}
