// Code generated by MockGen. DO NOT EDIT.
// Source: internal/service/service.go

// Package service is a generated GoMock package.
package service

import (
	context "context"
	reflect "reflect"

	models "github.com/alserok/preview_proxy/server/internal/service/models"
	gomock "github.com/golang/mock/gomock"
)

// MockService is a mock of Service interface.
type MockService struct {
	ctrl     *gomock.Controller
	recorder *MockServiceMockRecorder
}

// MockServiceMockRecorder is the mock recorder for MockService.
type MockServiceMockRecorder struct {
	mock *MockService
}

// NewMockService creates a new mock instance.
func NewMockService(ctrl *gomock.Controller) *MockService {
	mock := &MockService{ctrl: ctrl}
	mock.recorder = &MockServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockService) EXPECT() *MockServiceMockRecorder {
	return m.recorder
}

// GetThumbnails mocks base method.
func (m *MockService) GetThumbnails(ctx context.Context, req models.DownloadThumbnailsReq) (models.DownloadThumbnailsRes, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetThumbnails", ctx, req)
	ret0, _ := ret[0].(models.DownloadThumbnailsRes)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetThumbnails indicates an expected call of GetThumbnails.
func (mr *MockServiceMockRecorder) GetThumbnails(ctx, req interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetThumbnails", reflect.TypeOf((*MockService)(nil).GetThumbnails), ctx, req)
}
