name: dev (CI)
on:
  push:
    branches:
      - dev

jobs:
  lint:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        directory: [ server ]
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Go environment
        uses: actions/setup-go@v3
        with:
          go-version: '1.23'

      - name: Install Go dependencies
        run: |
          cd ${{ matrix.directory }}
          go mod tidy

      - name: Run linters
        uses: golangci/golangci-lint-action@v4
        with:
          working-directory: ${{ matrix.directory }}

  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        directory: [ server ]
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Go environment
        uses: actions/setup-go@v3
        with:
          go-version: '1.23'

      - name: Install Go dependencies
        run: |
          cd ${{ matrix.directory }}
          go mod tidy

      - name: Run tests
        run: |
          cd ${{ matrix.directory }}
          go test ./...